version: '3.1'
services:
  teamspeak:
    user: root
    image: teamspeak
    restart: always
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    volumes:
      - ./data/:/var/ts3server/
    environment:
      TS3SERVER_LICENSE: accept
      TS3SERVER_PASSWORD: leolinuxcoolagreatpassword